name: Development

on:
  push:
    branches:
      - feat/WTEL-6646/actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@7a10c22563df4852961b55bb5513c1633450db3e
    with:
      development-branch: master
      triggered-branch: master # ${{ github.ref_name }}
      build-number: ${{ github.run_number }}

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/c-build.yml@8b0b5e2472b8fddabbaf87262d1b0170182c3058
    with:
      version: ${{ needs.prepare.outputs.version }}
      prerelease: freeswitch
      package-name: freeswitch-mod-grpc
      package-description: "FreeSWITCH: Webitel gRPC module"
      package-contents: src=mod_grpc.so dst=/usr/lib/freeswitch/mod/mod_grpc.so type=file mode=0644
      upload-artifact-pattern: build/mod_grpc.so
      args: |
        -DMOD_BUILD_VERSION="${{ github.run_number }}, commit: ${{ github.sha }}/${{ github.ref_name }}" \
        -DFREESWITCH_INCLUDE_DIR=/usr/include/freeswitch \
        -DINSTALL_MOD_DIR=/usr/local/freeswitch/mod \
        -DCMAKE_BUILD_TYPE=Release

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@445c69dffb531031e9c13fb029cb8bd2f7cc2ac7
    secrets: inherit
    with:
      component: ${{ needs.prepare.outputs.component }}
      repository-environment: acceptance
