name: Development

on:
  push:
    branches:
      - feat/WTEL-6646/actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile module
    runs-on: [ arc-c-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure build files
        uses: threeal/cmake-action@v2.1.0
        env:
          MOD_BUILD_VERSION: "${{ github.run_number }}, commit: ${{ github.sha }}/${{ github.ref_name }}"

        with:
          build-dir: build
          run-build: false
          options: |
            MOD_BUILD_VERSION="$MOD_BUILD_VERSION"
            FREESWITCH_INCLUDE_DIR=/usr/include/freeswitch
            INSTALL_MOD_DIR=/usr/local/freeswitch/mod
            CMAKE_BUILD_TYPE=Release


      - name: Compile
        uses: threeal/cmake-action@v2.1.0
        with:
          build-dir: build
          build-args: |
            -- -j$(nproc)

      - name: Test
        run: ls -lsa ./*
