name: Development

on:
  push:
    branches:
      - feat/WTEL-6646/actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile module
    runs-on: [ arc-c-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure build files
        run: |
          cmake -B build \
            -DMOD_BUILD_VERSION="${{ github.run_number }}, commit: ${{ github.sha }}/${{ github.ref_name }}" \
            -DFREESWITCH_INCLUDE_DIR=/usr/include/freeswitch \
            -DINSTALL_MOD_DIR=/usr/local/freeswitch/mod \
            -DCMAKE_BUILD_TYPE=Release

      - name: Get number of CPU cores
        id: nproc
        run: echo "cpu_cores=$(nproc)" >> $GITHUB_OUTPUT

      - name: Compile
        run: cmake --build build -j ${{ steps.nproc.outputs.cpu_cores }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-source
          compression-level: 9
          path: build/mod_grpc.so

  build:
    name: Build package
    needs: [ compile ]
    runs-on: [ arc-c-runner-set ]
    outputs:
      freeswitch-version: ${{ steps.fs_version.outputs.FREESWITCH_VERSION }}
      file: ${{ steps.build.outputs.packages }}

    steps:
      - name: Get Freeswitch version
        id: fs_version
        run: |
          FREESWITCH_VERSION=$(freeswitch -version | cut -f 3 -d " " | cut -f 1 -d "-")
          echo "FREESWITCH_VERSION=$FREESWITCH_VERSION" >> $GITHUB_OUTPUT

      - name: Download compiled file
        uses: actions/download-artifact@v4
        with:
          name: build-source

      - name: Build package
        id: build
        uses: webitel/reusable-workflows/actions/nfpm-build-action@main
        with:
          nfpm-version: latest
          formats: deb
          target: dist
          package-name: freeswitch-mod-grpc
          package-description: Webitel GRPC for FreeSWITCH
          maintainer: Webitel <support@webitel.com>
          homepage: https://webitel.com
          arch: amd64
          platform: linux
          version: ${{ steps.fs_version.outputs.FREESWITCH_VERSION }}
          release: ${{ github.run_number }}
          contents: |
            src=mod_grpc.so dst=/usr/lib/freeswitch/mod/mod_grpc.so type=file

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-packages
          compression-level: 9
          path: dist

  release:
    name: Release assets
    needs: [ build ]
    runs-on: [ arc-c-runner-set ]
    permissions:
      contents: write

    env:
      VERSION: ${{ needs.build.outputs.freeswitch-version }}-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: build-packages

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: $VERSION
          name: Release $VERSION
          draft: false
          make_latest: true
          generate_release_notes: true
          files: |
            ${{ needs.build.outputs.file }}
