name: Development

on:
  push:
    branches:
      - feat/WTEL-6646/actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile module
    runs-on: [ arc-c-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure build files
        run: |
          cmake -B build \
            -DMOD_BUILD_VERSION="${{ github.run_number }}, commit: ${{ github.sha }}/${{ github.ref_name }}" \
            -DFREESWITCH_INCLUDE_DIR=/usr/include/freeswitch \
            -DINSTALL_MOD_DIR=/usr/local/freeswitch/mod \
            -DCMAKE_BUILD_TYPE=Release

      - name: Get number of CPU cores
        id: nproc
        run: echo "cpu_cores=$(nproc)" >> $GITHUB_OUTPUT

      - name: Compile
        run: cmake --build build -j ${{ steps.nproc.outputs.cpu_cores }}

      - name: Test
        run: ls -lsa ./build/*
